
name: ttwkziye

on:
  workflow_dispatch:
  schedule:
     - cron: '5 18 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        ZFBWK_HEADER: ${{ secrets.ZFBWK_HEADER }}
        ZFBWK_BODY: ${{ secrets.ZFBWK_BODY }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        if: env.ZFBWK_HEADER
        run: |
          npm install
      - name: '运行 【支付宝挖矿】'
        if: env.ZFBWK_HEADER
        run: |
          node Task/ttwkziye.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          
          
